env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 12
rules:
  comma-dangle: error
  curly: error
  indent:
    - error
    - tab
    - SwitchCase: 1
      ignoredNodes: [ObjectExpression]
  semi: 
    - error
    - always
  quotes: [error, single, { avoidEscape: true }]
  prefer-arrow-callback: error
